Repository 10up/classifai, pull requests merged in 2019-07, with the labels that each got.

#97 Update changelog to 10up standard
  CHANGELOG.md
Labels: documentation

#96 Fix NLU Settings and Wp-CLI
  classifai.php
  includes/Classifai/Command/ClassifaiCommand.php
  includes/Classifai/Helpers.php
  includes/Classifai/Plugin.php
  includes/Classifai/Providers/AWS/Comprehend.php
  includes/Classifai/Providers/Azure/ComputerVision.php
  includes/Classifai/Providers/Provider.php
  includes/Classifai/Providers/Watson/NLU.php
  includes/Classifai/Services/Service.php
  includes/Classifai/Services/ServicesManager.php
Labels: bug

#90 Hotfix/87
  config.php
  includes/Classifai/Services/ServicesManager.php
Labels: bug, documentation

#94 Add Data Gathering section to README
  README.md
Labels: documentation, enhancement

#103 Don't try to run Watson NLU when it's not fully configured
  includes/Classifai/Admin/SavePostHandler.php
Labels: bug

#106 Register _classifai_error meta as single
  includes/Classifai/Plugin.php
Labels: bug
