Repository 10up/classifai, pull requests merged in 2019-09, with the labels that each got.

#125 Expanding Computer Vision for image classification
  includes/Classifai/Providers/Azure/ComputerVision.php
  includes/Classifai/Providers/Provider.php
  includes/Classifai/Services/ImageProcessing.php
  includes/Classifai/Taxonomy/AbstractTaxonomy.php
  includes/Classifai/Taxonomy/ImageTagTaxonomy.php
Labels: enhancement

#132 Fix/npm audit
  package-lock.json
  package.json
  src/js/editor.js
Labels: dependencies

#134 Add image tags and alt text to search
  includes/Classifai/Providers/Azure/ComputerVision.php
Labels: enhancement

#137 Add readme note about local/inaccessible images
  README.md
Labels: documentation

#110 Computer Vision - send next largest image when full is too big
  includes/Classifai/Providers/Azure/ComputerVision.php
  tests/Classifai/Providers/Azure/ComputerVisionTest.php
Labels: enhancement

#108 Add plugin debug information to the Site Health screen
  includes/Classifai/Admin/DebugInfo.php
  includes/Classifai/Plugin.php
  includes/Classifai/Providers/Azure/ComputerVision.php
  includes/Classifai/Providers/Provider.php
  includes/Classifai/Providers/Watson/NLU.php
  includes/Classifai/Services/Service.php
  includes/Classifai/Services/ServicesManager.php
  tests/Classifai/Admin/DebugInfoTest.php
  tests/Classifai/Azure/ComputerVisionTest.php
  tests/Classifai/Services/ServicesManagerTest.php
  tests/Classifai/Watson/NLUSettingsTest.php
Labels: enhancement

#142 Show admin menu notice (!) for lack of registration instead of specific service setup
  includes/Classifai/Services/ServicesManager.php
Labels: bug

#144 Add a dev version notice
  .github/action-release/entrypoint.sh
  classifai.php
Labels: enhancement
