Repository 10up/classifai, pull requests merged in 2020-02, with the labels that each got.

#149 Add smart image cropping with Computer Vision
  .gitignore
  README.md
  includes/Classifai/Helpers.php
  includes/Classifai/Providers/Azure/ComputerVision.php
  includes/Classifai/Providers/Azure/SmartCropping.php
  tests/Classifai/HelpersTest.php
  tests/Classifai/Providers/Azure/ComputerVisionTest.php
  tests/Classifai/Providers/Azure/SmartCroppingTest.php
  tests/bootstrap.php
Labels: enhancement

#181 Syntax issue on line 29
  README.md
Labels: documentation

#168 remove double slashes in the script url
  includes/Classifai/Providers/Watson/NLU.php
Labels: bug

#169 Fix: Wrong setting link in the notice after activation
  includes/Classifai/Admin/Notifications.php
Labels: bug

#172 Fix: Saving protected meta in Gutenberg
  includes/Classifai/Plugin.php
Labels: bug

#174 update: PHP version error message
  classifai.php
Labels: enhancement

#170 Add: Registering ClassifAI account docs.
  README.md
Labels: documentation

#184 Add pricing details to new section in readme
  README.md
Labels: documentation

#173 Add: WP Admin menu icon
  assets/img/menu-icon.svg
  includes/Classifai/Services/ServicesManager.php
Labels: enhancement

#180 Add: service provider request response info to Site Health Info screen
  includes/Classifai/Providers/Azure/ComputerVision.php
  includes/Classifai/Providers/Azure/SmartCropping.php
  includes/Classifai/Providers/Watson/NLU.php
  includes/Classifai/Watson/Classifier.php
  tests/Classifai/Azure/ComputerVisionTest.php
  tests/Classifai/Watson/NLUSettingsTest.php
Labels: enhancement

#175 Update: Better Watson credentials settings
  README.md
  includes/Classifai/Providers/Watson/NLU.php
  languages/classifai.pot
  src/js/admin.js
  webpack.config.js
Labels: enhancement

#135 Process Existing Images with Computer Vision
  .eslintrc.json
  README.md
  includes/Classifai/Providers/Azure/ComputerVision.php
  includes/Classifai/Providers/Provider.php
  includes/Classifai/Services/ImageProcessing.php
  src/js/admin.js
  src/js/media.js
  webpack.config.js
Labels: enhancement

#164 Fix: Pages are not being scanned by Language Processing
  includes/Classifai/Admin/SavePostHandler.php
  includes/Classifai/Providers/Watson/NLU.php
  tests/Classifai/Admin/SavePostHandlerTest.php
Labels: bug

#179 Add: WP Acceptance
  .travis.yml
  composer.json
  composer.lock
  includes/Classifai/Command/RSSImporterCommand.php
  package.json
  tests/e2e/wpacceptance/Activation.php
  tests/e2e/wpacceptance/Settings.php
  tests/e2e/wpacceptance/bootstrap.php
  tests/e2e/wpacceptance/includes/TestCaseBase.php
  wpacceptance.json
Labels: enhancement

#178 Add: Ability to process already created content
  includes/Classifai/Admin/BulkActions.php
  includes/Classifai/Plugin.php
Labels: enhancement

#177 Add: WP-CLI command to bulk classify images
  README.md
  includes/Classifai/Command/ClassifaiCommand.php
Labels: enhancement
