Repository 10up/classifai, pull requests merged in 2020-10, with the labels that each got.

#233 Ensure manual image scanning still works if the automatic scanning is turned off
  includes/Classifai/Providers/Azure/ComputerVision.php
Labels: bug

#237 bump WP tested-up-to 5.5.1
  README.md
  readme.txt
Labels: documentation

#235 Ensure we use the largest image size possible when scanning from the single edit view
  includes/Classifai/Providers/Azure/ComputerVision.php
Labels: bug

#231 Add better error handling for manual scanning of alt text or image tags
  includes/Classifai/Providers/Azure/ComputerVision.php
  includes/Classifai/Services/ImageProcessing.php
  src/js/media.js
Labels: bug

#250 Fixes azure storage compatibility issue with classifai.
  includes/Classifai/Providers/Azure/ComputerVision.php
Labels: bug

#247 Don't default to the `post` post type, if no other post types are selected
  includes/Classifai/Helpers.php
  tests/Classifai/HelpersTest.php
  tests/Classifai/Taxonomy/TaxonomyFactoryTest.php
Labels: bug

#249 Don't process items if no Language Processing features are enabled
  includes/Classifai/Admin/SavePostHandler.php
  includes/Classifai/Helpers.php
Labels: bug

#245 Remove media from language processing settings
  includes/Classifai/Helpers.php
  includes/Classifai/Providers/Watson/NLU.php
  tests/e2e/wpacceptance/NaturalLanguageProcessing.php
Labels: enhancement

#252 Fix: Smart cropping for existing images
  includes/Classifai/Providers/Azure/ComputerVision.php
  includes/Classifai/Services/ImageProcessing.php
  src/js/media.js
Labels: enhancement
